Remove tools/libinput-record from build
tools/libinput-record does not build on FreeBSD because of missing
stuff:

../tools/libinput-record.c:1734:57: error: use of undeclared identifier 'versionsort'
        ndev = scandir("/dev/input", &namelist, is_event_node, versionsort);
                                                               ^
../tools/libinput-record.c:1786:57: error: use of undeclared identifier 'versionsort'
        ndev = scandir("/dev/input", &namelist, is_event_node, versionsort);